apiVersion: v1
kind: Secret
metadata:
  name: tradinggate-app-secrets
  namespace: tradinggate-demo
type: Opaque
stringData:
  TRADING_DB_USER: trading_user
  TRADING_DB_PASSWORD: trading_pass
  LEDGER_DB_USER: ledger_user
  LEDGER_DB_PASSWORD: ledger_pass
  AUTH_SECRET_KEY: changeme
