apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-postgres-pvc
  namespace: tradinggate-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: trading-postgres
  namespace: tradinggate-demo
spec:
  selector:
    app: trading-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-postgres
  namespace: tradinggate-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-postgres
  template:
    metadata:
      labels:
        app: trading-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: trading_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tradinggate-app-secrets
                  key: TRADING_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tradinggate-app-secrets
                  key: TRADING_DB_PASSWORD
          volumeMounts:
            - name: trading-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: trading-postgres-data
          persistentVolumeClaim:
            claimName: trading-postgres-pvc
