apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tradinggate
resources:
  - namespace.yaml
  - configmap.yaml
  - api.yaml
  - projection.yaml
  - worker.yaml
  - risk.yaml
  - clearing.yaml
